/**
 * Gold She Mesh — Hub Node Server (PC)
 * 
 * V2.0: Raw TCP Refactor (Pillar 1)
 * Enforces industrial socket standards, JSON-newline protocol, 
 * and Zombie Socket Annihilation.
 */

import net from 'node:net';
import EventEmitter from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import { webcrypto } from 'node:crypto';
const { subtle } = webcrypto;
import { HubCryptoEngine } from './cryptoengine';
import { HubOfflineStore } from './offline-store';
import { PairingManager } from './paring-manager';
import { sseRegistry, telemetryRegistry } from './sse-registry';
import { DeltaProcessor } from './delta-processor';
import { KhataEngine } from '../khata-engine';
import { TCPCrypto } from './tcp-crypto';
import { IndustryType, VOCABULARIES } from '../constants/vocabulary';
import { hubWorkerPool } from './worker-pool';
import { hubBinaryLogger } from './binary-logger';
import { configManager } from './config-manager';
import {
  buildPacket,
  generateUUID,
  HUB_PORT,
  MAX_DEVICES,
  HEARTBEAT_INTERVAL_MS,
  type MeshPacket,
  type MessageType,
  type DeviceIdentity,
  type EncryptedEnvelope,
  type HandshakeInitPayload,
  type HandshakeAckPayload,
  type PairingValidatePayload,
  type PairingAcceptPayload,
  type KhataEntryPayload,
} from '../Shared/mesh-protocol';
import { ForensicMonitor } from './forensic-monitor';
import { JWTService } from './security-service';



// ─────────────────────────────────────────────────────────────

type HandshakeState = 'PENDING_PAIRING' | 'PENDING_HANDSHAKE' | 'ESTABLISHED';

interface ConnectedDevice {
  socket: net.Socket;
  deviceId: string;
  identity: DeviceIdentity;
  state: HandshakeState;
  /** Buffer for newline-delimited JSON */
  buffer: string;
  /** Ephemeral key pair generated by hub for this session */
  ephemeralBundle?: Awaited<ReturnType<HubCryptoEngine['generateEphemeralBundle']>>;
  seqCounter: number;
  lastHeartbeat: number;
  /** MODIFICATION 1: Zombie Annihilation Timer */
  handshakeTimer?: NodeJS.Timeout;
  /** GAP 2: Omnora Sync Window */
  syncOffset: number;
  /** GAP 3: Network Telemetry */
  latencyMs: number;
  lastPingSentAt: number;
  /** V9.0: Memory Leak Prevention */
  abortController: AbortController;
}

// ─────────────────────────────────────────────────────────────

export class HubNodeServer extends EventEmitter {
  private server: net.Server | null = null;
  private readonly nodes = new Map<string, ConnectedDevice>();
  /** Track all sockets for graceful annihilation */
  private readonly activeSockets = new Set<net.Socket>();

  private readonly crypto = new HubCryptoEngine();
  readonly store: HubOfflineStore;
  readonly pairing: PairingManager;
  readonly deltaProcessor: DeltaProcessor;
  private readonly forensic: ForensicMonitor;
  private readonly startTime = Date.now();

  public readonly hubDeviceId: string;


  private hubIdentity: DeviceIdentity;
  private hubSeq = 0;
  private heartbeatInterval: ReturnType<typeof setInterval> | null = null;

  constructor(hubName = 'Gold She Hub PC') {
    super();
    this.store = new HubOfflineStore();

    const savedId = this.store.getHubDeviceId();
    if (savedId) {
      this.hubDeviceId = savedId;
      console.info(`[HubServer] Restored identity: ${savedId}`);
    } else {
      this.hubDeviceId = generateUUID();
      this.store.saveHubDeviceId(this.hubDeviceId);
      console.info(`[HubServer] New identity: ${this.hubDeviceId}`);
    }

    this.hubIdentity = {
      deviceId: this.hubDeviceId,
      deviceName: hubName,
      deviceType: 'hub_pc',
      ecdhPublicKey: '', 
      registeredAt: Date.now(),
      lastSeen: Date.now(),
      isOnline: true,
    };

    this.pairing = new PairingManager(this.store, this.hubDeviceId);
    this.deltaProcessor = new DeltaProcessor(this.store.getDb());
    this.forensic = ForensicMonitor.getInstance(this.store);

    /** GAP 1: Handle packets from Secure WebSocket Bridge */
    this.on('bridge-packet', (packet: MeshPacket) => {
      this.handleBridgePacket(packet).catch(err => {
        console.error('[HubServer] Bridge packet processing error:', err);
      });
    });
  }

  // ─── Lifecycle ─────────────────────────────────────────────

  private static instance: HubNodeServer | null = null;

  static getInstance(): HubNodeServer {
    if (!HubNodeServer.instance) {
      HubNodeServer.instance = new HubNodeServer();
    }
    return HubNodeServer.instance;
  }

  async start(): Promise<void> {
    hubWorkerPool.start();
    this.server = net.createServer((socket) => this.onConnection(socket));

    this.server.on('error', (err) => {
      console.error('[HubServer] TCP Server Error:', err);
      this.emit('error', err);
    });

    this.server.listen(HUB_PORT, '0.0.0.0', () => {
      console.info(`[HubServer] Pillar 1 Raw TCP Mesh online at port ${HUB_PORT}`);
      this.emit('started');
    });

    this.store.upsertDevice(this.hubIdentity);

    this.heartbeatInterval = setInterval(() => {
      const deadline = Date.now() - HEARTBEAT_INTERVAL_MS * 2.5;
      for (const [deviceId, node] of this.nodes) {
        if (node.lastHeartbeat < deadline) {
          console.warn(`[HubServer] Heartbeat timeout — dropping ${deviceId}`);
          node.socket.destroy();
          this.handleDisconnect(node);
        } else if (node.state === 'ESTABLISHED') {
          // Send ping for RTT calculation
          node.lastPingSentAt = Date.now();
          this.sendToDevice(deviceId, buildPacket('HEARTBEAT', this.hubDeviceId, deviceId, this.nextSeq(), {}));
        }
      }
      this.store.expireOldPairingCodes();
    }, HEARTBEAT_INTERVAL_MS);

    // PILLAR 4: THE JANITOR (Storage Cleanup)
    // Runs every 24 hours to ensure SSD doesn't fill up with CCTV snippets.
    setInterval(() => this.runJanitor(), 24 * 60 * 60 * 1000);
    // Run once on boot
    this.runJanitor();
  }

  private runJanitor(): void {
    const snippetsDir = path.join(process.cwd(), 'public', 'snippets');
    if (!fs.existsSync(snippetsDir)) return;

    console.info('[HubServer] Janitor: Starting storage audit...');
    const now = Date.now();
    const RETENTION_MS = 7 * 24 * 60 * 60 * 1000; // 7 Days

    fs.readdir(snippetsDir, (err: Error | null, files: string[]) => {
      if (err) return;
      files.forEach((file: string) => {
        if (!file.endsWith('.mp4')) return;
        
        const filePath = path.join(snippetsDir, file);
        fs.stat(filePath, (err: Error | null, stats: fs.Stats) => {
          if (err) return;
          if (now - stats.mtimeMs > RETENTION_MS) {
            console.info(`[HubServer] Janitor: Purging old snippet ${file}`);
            fs.unlink(filePath, () => {});
          }
        });
      });
    });
  }

  /** MODIFICATION 2: Graceful Shutdown (EADDRINUSE protection) */
  stop(): void {
    console.info('[HubServer] Initiating graceful shutdown...');
    if (this.heartbeatInterval) clearInterval(this.heartbeatInterval);
    
    // Annihilate all active sockets immediately
    for (const socket of this.activeSockets) {
      socket.destroy();
    }
    this.activeSockets.clear();

    if (this.server) {
      this.server.close();
      this.server = null;
    }
    
    this.store.close();
    this.emit('stopped');
    console.info('[HubServer] Shutdown complete.');
  }

  // ─── Connection Handling ────────────────────────────────────

  private onConnection(socket: net.Socket): void {
    const ip = socket.remoteAddress ?? 'unknown';
    this.activeSockets.add(socket);

    if (this.nodes.size >= MAX_DEVICES) {
      console.warn(`[HubServer] Capacity reached. Rejecting ${ip}`);
      this.sendRawSocket(socket, this.buildErrorPacket('MAX_DEVICES_REACHED', 'Hub at capacity', false));
      socket.destroy();
      return;
    }

    const abortController = new AbortController();
    const { signal } = abortController;

    const device: ConnectedDevice = {
      socket,
      deviceId: '',
      identity: {} as DeviceIdentity,
      state: 'PENDING_PAIRING',
      buffer: '',
      seqCounter: 0,
      lastHeartbeat: Date.now(),
      syncOffset: 0,
      latencyMs: 0,
      lastPingSentAt: 0,
      abortController,
    };

    /** MODIFICATION 1: Zombie Socket Annihilation (3000ms) */
    device.handshakeTimer = setTimeout(() => {
      if (device.state !== 'ESTABLISHED') {
        console.warn(`[HubServer] Zombie detected (${ip}). Destroying socket.`);
        socket.destroy();
      }
    }, 3000);

    const onData = (chunk: Buffer) => this.onSocketData(device, chunk);
    const onError = (err: Error) => {
      console.error(`[HubServer] Socket error from ${ip}:`, err.message);
      socket.destroy();
    };

    socket.on('data', onData);
    socket.on('error', onError);
    
    signal.addEventListener('abort', () => {
      socket.off('data', onData);
      socket.off('error', onError);
    }, { once: true });

    socket.on('close', () => {
      this.activeSockets.delete(socket);
      if (device.handshakeTimer) clearTimeout(device.handshakeTimer);
      device.abortController.abort(); // Kill all associated listeners
      this.handleDisconnect(device);
    });

    console.info(`[HubServer] New raw connection from ${ip}`);
  }

  private onSocketData(device: ConnectedDevice, chunk: Buffer): void {
    // 1. RAW BINARY LOGGING
    hubBinaryLogger.log(chunk);

    device.buffer += chunk.toString('utf8');
    
    let boundaryIndex: number;
    while ((boundaryIndex = device.buffer.indexOf('\n')) !== -1) {
      const line = device.buffer.slice(0, boundaryIndex).trim();
      device.buffer = device.buffer.slice(boundaryIndex + 1);
      
      if (line) {
        // 2. OFF-LOAD TO WORKER POOL
        const secret = this.store.getSystemSecret() || 'goldshe-mesh-default-secret-v1';
        const taskId = generateUUID();

        hubWorkerPool.execute({
          id: taskId,
          type: 'DECRYPT_JSON', // Default for now, can detect binary/json later
          payload: line,
          secret
        }).then(result => {
          if (result.success) {
            this.handleProcessedPacket(device, result.data).catch(err => {
              console.error('[HubServer] Packet handling error:', err);
            });
          } else {
            console.error(`[HubServer:Worker] Processing failed:`, result.error);
          }
        });
      }
    }
  }

  /**
   * New handler for packets that have been decrypted and parsed by workers.
   */
  private async handleProcessedPacket(device: ConnectedDevice, packet: MeshPacket): Promise<void> {
    // 1. HEARTBEAT LATENCY TRACKING
    if (packet.type === 'HEARTBEAT' || packet.type === 'HEARTBEAT_ACK') {
      device.lastHeartbeat = Date.now();
      
      if (packet.type === 'HEARTBEAT_ACK' && device.lastPingSentAt > 0) {
        device.latencyMs = Date.now() - device.lastPingSentAt;
        
        // Flag Weak Connection (> 500ms)
        const quality = device.latencyMs > 500 ? 'weak' : 'stable';
        if (quality === 'weak') {
          console.warn(`[HubServer] WEAK CONNECTION detected for ${device.deviceId}: ${device.latencyMs}ms`);
        }

        // Update telemetry
        telemetryRegistry.broadcast({
          event: 'telemetry',
          data: {
            deviceId: device.deviceId,
            latencyMs: device.latencyMs,
            connectionQuality: quality
          }
        });
      }

      if (packet.type === 'HEARTBEAT') {
        this.sendRawSocket(device.socket, buildPacket('HEARTBEAT_ACK', this.hubDeviceId, packet.from, this.nextSeq(), {}));
      }
      return;
    }

    // 2. FORENSIC TRACKING (Scans)
    if (packet.type === 'KHATA_ENTRY' || packet.type === 'AI_TELEMETRY') {
      this.forensic.trackScan(device.deviceId, device.identity.deviceName || 'Unknown Node');
    }

    // Handshake Flow
    if (packet.type === 'PAIRING_VALIDATE') {
      await this.handlePairingValidate(device, packet);
      return;
    }

    if (packet.type === 'HANDSHAKE_INIT') {
      await this.handleHandshakeInit(device, packet);
      return;
    }

    if (packet.type === 'HANDSHAKE_COMPLETE') {
      await this.handleHandshakeComplete(device);
      return;
    }

    // Authenticated Routing
    if (device.state !== 'ESTABLISHED' || device.deviceId !== packet.from) {
      this.sendRawSocket(device.socket, this.buildErrorPacket('AUTH_REQUIRED', 'Establish session first', false));
      return;
    }

    device.lastHeartbeat = Date.now();

    // The packet payload is already decrypted if it was a specialized industrial event, 
    // or we might need to route it.
    // If the worker returned a full MeshPacket with decrypted data:
    await this.routeMessage(device, packet, packet.payload);
  }

  private async processPacket(device: ConnectedDevice, raw: string): Promise<void> {
    let packet: MeshPacket;
    try {
      packet = JSON.parse(raw) as MeshPacket;
    } catch {
      console.error('[HubServer] Invalid JSON received. Dropping line.');
      return;
    }

    // Heartbeat (Cleartext)
    if (packet.type === 'HEARTBEAT') {
      device.lastHeartbeat = Date.now();
      this.sendRawSocket(device.socket, buildPacket('HEARTBEAT_ACK', this.hubDeviceId, packet.from, this.nextSeq(), {}));
      return;
    }

    // Handshake Flow
    if (packet.type === 'PAIRING_VALIDATE') {
      await this.handlePairingValidate(device, packet);
      return;
    }

    if (packet.type === 'HANDSHAKE_INIT') {
      await this.handleHandshakeInit(device, packet);
      return;
    }

    if (packet.type === 'HANDSHAKE_COMPLETE') {
      await this.handleHandshakeComplete(device);
      return;
    }

    // Authenticated Routing
    if (device.state !== 'ESTABLISHED' || device.deviceId !== packet.from) {
      this.sendRawSocket(device.socket, this.buildErrorPacket('AUTH_REQUIRED', 'Establish session first', false));
      return;
    }

    device.lastHeartbeat = Date.now();

    // Decrypt Envelope
    try {
      const envelope = JSON.parse(packet.payload) as EncryptedEnvelope;
      const innerPayload = await this.crypto.decrypt(envelope, packet.from);
      await this.routeMessage(device, packet, innerPayload);
    } catch (err) {
      console.error(`[HubServer] Decrypt failed from ${packet.from}:`, err);
      this.forensic.trackError(packet.from, 'Unknown Node', (err as Error).message);
      this.sendToDevice(packet.from, this.buildErrorPacket('DECRYPT_FAILED', 'Security violation', true));
    }
  }

  // ─── Message Routing & Handshake ─────────────────────────────

  private async handlePairingValidate(device: ConnectedDevice, packet: MeshPacket): Promise<void> {
    const payload = JSON.parse(packet.payload) as PairingValidatePayload;
    const result = this.pairing.validate(payload.pairingCode, payload.deviceIdentity.deviceId, this.nodes.size);

    if (!result.valid) {
      this.sendRawSocket(device.socket, this.buildErrorPacket('AUTH_FAILED', result.reason ?? 'Invalid code', false));
      device.socket.destroy();
      return;
    }

    const identity = { ...payload.deviceIdentity, isOnline: true, lastSeen: Date.now() };
    this.store.upsertDevice(identity);

    device.deviceId = identity.deviceId;
    device.identity = identity;
    device.state = 'PENDING_HANDSHAKE';

    // OMNORA SYNC WINDOW: Assign unique offset (250ms steps)
    device.syncOffset = (this.nodes.size * 250) % 5000;

    const accept: PairingAcceptPayload = {
      assignedDeviceId: identity.deviceId,
      hubIdentity: this.hubIdentity,
      registeredDevices: this.store.getAllDevices(),
      bridgeToken: JWTService.issueToken(identity.deviceId, identity.deviceName),
      // @ts-expect-error - Adding dynamic property for the directive

      syncOffset: device.syncOffset,
    };

    this.sendRawSocket(device.socket, buildPacket('PAIRING_ACCEPT', this.hubDeviceId, identity.deviceId, this.nextSeq(), accept));
    console.info(`[HubServer] Device paired (Sync Offset: ${device.syncOffset}ms): ${identity.deviceName}`);
  }

  private async handleHandshakeInit(device: ConnectedDevice, packet: MeshPacket): Promise<void> {
    if (device.state !== 'PENDING_HANDSHAKE') return;

    const init = JSON.parse(packet.payload) as HandshakeInitPayload;
    const peerKey = await this.crypto.importPeerPublicKey(init.ephemeralPublicKey);
    const bundle = await this.crypto.generateEphemeralBundle();
    device.ephemeralBundle = bundle;

    // Derive session key
    await this.crypto.deriveSessionKey(bundle.keyPair.privateKey, peerKey, packet.from);
    
    // Compute verify token using the same logic as the engine (needs raw bits)
    const rawBits = await subtle.deriveBits(
      { name: 'ECDH', public: peerKey },
      bundle.keyPair.privateKey,
      256
    );
    const verifyToken = HubCryptoEngine.computeVerifyToken(rawBits, init.nonce);

    const ack: HandshakeAckPayload = {
      identity: this.hubIdentity,
      ephemeralPublicKey: bundle.publicBase64,
      nonceEcho: init.nonce, 
      verifyToken, 
    };

    this.sendRawSocket(device.socket, buildPacket('HANDSHAKE_ACK', this.hubDeviceId, packet.from, this.nextSeq(), ack));
  }

  private async handleHandshakeComplete(device: ConnectedDevice): Promise<void> {
    if (device.state !== 'PENDING_HANDSHAKE') return;

    device.state = 'ESTABLISHED';
    if (device.handshakeTimer) clearTimeout(device.handshakeTimer);
    
    this.nodes.set(device.deviceId, device);
    console.info(`[HubServer] Session ESTABLISHED: ${device.deviceId}`);

    // Broadcast online status
    this.broadcastStatus(device.deviceId, true);
  }

  private async routeMessage(_node: ConnectedDevice, packet: MeshPacket, inner: unknown): Promise<void> {
    // ── Pillar 3: AI Telemetry ──────────────────────────────
    if (packet.type === 'AI_TELEMETRY') {
      telemetryRegistry.broadcast({
        event: 'ai-telemetry',
        data: inner,
      });
      return;
    }

    if (packet.type === 'TELEMETRY_BEAT') {
      telemetryRegistry.broadcast({
        event: 'telemetry',
        data: inner,
      });
      return;
    }

    // ── Pillar 5: Khata Ledger ──────────────────────────────
    if (packet.type === 'KHATA_ENTRY') {
      try {
        const payload = inner as KhataEntryPayload & { cameraId?: string };
        const entry = await KhataEngine.recordEntry({
          type: payload.type,
          amount: payload.amount,
          description: payload.description,
          workerName: payload.workerName,
          workerId: payload.workerId,
          snippetPath: `public/snippets/${payload.id}.mp4`
        });

        // PILLAR 4: Trigger AI Snippet Recording (Fire and Forget)
        // OMNORA V9.0: Tier Guard for Vision Trigger
        if (configManager.isFeatureEnabled('visionEnabled')) {
          fetch('http://localhost:5000/trigger-snippet', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
              uuid: payload.id,
              camera_id: payload.cameraId || 'DEFAULT' 
            })
          }).catch(err => console.warn('[HubServer] Vision Trigger Warning:', err.message));
        } else {
          console.debug('[HubServer] Vision Trigger skipped (Tier Restricted)');
        }

        sseRegistry.broadcast({
          event: 'khata-entry',
          data: entry,
        });
      } catch (err) {
        console.error('[HubServer] Khata Ledger Error:', err);
      }
      return;
    }

    // ── Messenger & Presence ───────────────────────────────
    if (packet.type === 'TEXT_MESSAGE' || packet.type === 'PHOTO_MESSAGE') {
      sseRegistry.broadcast({
        event: 'message',
        data: { packet, payload: inner },
      });
    }
    
    console.debug(`[HubServer] Routed ${packet.type} from ${packet.from}`);
  }

  // ─── Helpers ───────────────────────────────────────────────

  private sendRawSocket(socket: net.Socket, packet: MeshPacket): void {
    if (!socket.writable) return;
    
    const raw = JSON.stringify(packet);
    const secret = this.store.getSystemSecret();

    if (secret) {
      try {
        const encrypted = TCPCrypto.encrypt(raw, secret);
        socket.write(encrypted + '\n');
        return;
      } catch (err) {
        console.error('[HubServer] Encryption failed:', (err as Error).message);
      }
    }

    socket.write(raw + '\n');
  }

  sendToDevice(deviceId: string, packet: MeshPacket): void {
    const node = this.nodes.get(deviceId);
    if (node) {
      this.sendRawSocket(node.socket, packet);
    } else {
      // Might be a bridge-connected node
      this.emit('send-to-bridge', deviceId, packet);
    }
  }

  /**
   * BROADCAST: Send a packet to all ESTABLISHED nodes.
   */
  broadcast(type: MessageType, payload: object): void {
    const packet = buildPacket(type, this.hubDeviceId, 'broadcast', this.nextSeq(), payload);
    for (const node of this.nodes.values()) {
      if (node.state === 'ESTABLISHED') {
        this.sendRawSocket(node.socket, packet);
      }
    }
    // Also broadcast to secure bridge nodes
    this.emit('broadcast-to-bridge', packet);
  }

  /**
   * BROADCAST VOCABULARY: Notifies all field nodes of terminology changes.
   */
  broadcastVocabulary(industry: IndustryType): void {
    const vocab = VOCABULARIES[industry];
    if (!vocab) return;

    console.info(`[HubServer] Broadcasting Vocabulary: ${industry.toUpperCase()}`);
    this.broadcast('VOCABULARY_UPDATE', { 
      industry, 
      ...vocab 
    });
  }

  private nextSeq(): number {
    return ++this.hubSeq;
  }

  private buildErrorPacket(code: string, msg: string, fatal: boolean): MeshPacket {
    return buildPacket('ERROR', this.hubDeviceId, 'all', 0, { code, message: msg, fatal });
  }

  private handleDisconnect(device: ConnectedDevice): void {
    if (device.deviceId) {
      this.nodes.delete(device.deviceId);
      this.broadcastStatus(device.deviceId, false);
      this.store.setDeviceOnline(device.deviceId, false);
      console.info(`[HubServer] Device offline: ${device.deviceId}`);
    }
  }

  private async handleBridgePacket(packet: MeshPacket): Promise<void> {
    try {
      const envelope = JSON.parse(packet.payload) as EncryptedEnvelope;
      const innerPayload = await this.crypto.decrypt(envelope, packet.from);
      
      // Route using the same logic as TCP nodes
      // We pass a partial device object since routeMessage doesn't currently use the socket
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await this.routeMessage({ deviceId: packet.from } as any, packet, innerPayload);
    } catch (err) {
      console.error(`[HubServer] Bridge decryption failed from ${packet.from}:`, err);
    }
  }

  private broadcastStatus(deviceId: string, online: boolean): void {
    const event = online ? 'device-online' : 'device-offline';
    const data = online 
      ? { device: this.nodes.get(deviceId)?.identity } 
      : { deviceId, lastSeen: Date.now() };

    sseRegistry.broadcast({ event: event as 'device-online' | 'device-offline', data });
    telemetryRegistry.broadcast({ event: event as 'device-online' | 'device-offline', data });
  }

  /**
   * Returns a list of all currently connected node identities.
   */
  getConnectedDevices(): DeviceIdentity[] {
    return Array.from(this.nodes.values()).map(n => n.identity);
  }

  get uptime(): number {
    return Date.now() - this.startTime;
  }

  get connectedDeviceCount(): number {
    return this.nodes.size;
  }

  /**
   * KICK: Terminate a node's connection and remove it from the registry.
   */
  kickDevice(deviceId: string): void {
    const node = this.nodes.get(deviceId);
    if (node) {
      node.socket.destroy();
      this.nodes.delete(deviceId);
    }
    this.store.removeDevice(deviceId);
    this.broadcastStatus(deviceId, false);
    console.info(`[HubServer] Device kicked: ${deviceId}`);
  }

  /**
   * SEND ENCRYPTED: Sends a high-security encrypted payload to a specific node.
   */
  async sendEncrypted(deviceId: string, type: MessageType, payload: object): Promise<void> {

    const node = this.nodes.get(deviceId);
    
    // 1. Build the base packet for storage/bridge
    const packet = buildPacket(type, this.hubDeviceId, deviceId, this.nextSeq(), payload);

    // 2. If node is connected via TCP, encrypt with session key and send
    if (node && node.state === 'ESTABLISHED') {
      try {
        const envelope = await this.crypto.encrypt(payload, deviceId);
        const encryptedPacket = buildPacket(type, this.hubDeviceId, deviceId, packet.seq, envelope);
        this.sendRawSocket(node.socket, encryptedPacket);
        return;
      } catch (err) {
        console.error(`[HubServer] Session encryption failed for ${deviceId}:`, err);
        throw err;
      }
    }

    // 3. If node is offline or on bridge, let the bridge handle encryption
    this.emit('send-to-bridge', deviceId, packet);
  }
}





export const getHubServer = () => HubNodeServer.getInstance();